export const GET_ALL_PATIENT_LIST = "GET_ALL_PATIENT_LIST";
export const GET_ALL_PATIENT_LIST_FAILURE = "GET_ALL_PATIENT_LIST_FAILURE";
export const GET_ALL_PATIENT_LIST_SUCCESS = "GET_ALL_PATIENT_LIST_SUCCESS";

export const GET_PATIENT_DETAIL = "GET_PATIENT_DETAIL";
export const GET_PATIENT_DETAIL_SUCCESS = "GET_PATIENT_DETAIL_SUCCESS";
export const GET_PATIENT_DETAIL_FAILURE = "GET_PATIENT_DETAIL_FAILURE";

export const DELETING_PATIENT = "DELETING_PATIENT";
export const DELETING_PATIENT_SUCCESS = "DELETING_PATIENT_SUCCESS";
export const DELETING_PATIENT_FAILURE = "DELETING_PATIENT_FAILURE";

export const REGISTERING_PATIENT = "REGISTERING_PATIENT";
export const REGISTERING_PATIENT_SUCCESS = "REGISTERING_PATIENT_SUCCESS";
export const REGISTERING_PATIENT_FAILURE = "REGISTERING_PATIENT_FAILURE";

export const UPDATING_PATIENT = "UPDATING_PATIENT";
export const UPDATING_PATIENT_SUCCESS = "UPDATING_PATIENT_SUCCESS";
export const UPDATING_PATIENT_FAILURE = "UPDATING_PATIENT_FAILURE";

export const FETHING_HOSPITAL_LIST = "FETHING_HOSPITAL_LIST";
export const FETCHING_HOSPITAL_LIST_SUCCESS = "FETCHING_HOSPITAL_LIST_SUCCESS";
export const FETCHING_HOSPITAL_LIST_FAILURE = "FETCHING_HOSPITAL_LIST_FAILURE";

export const ADDING_HOSPITAL = "ADDING_HOSPITAL";
export const ADDING_HOSPITAL_SUCCESS = "ADDING_HOSPITAL_SUCCESS";
export const ADDING_HOSPITAL_FAILURE = "ADDING_HOSPITAL_FAILURE";

export const FETCHING_MY_PATIENT_LIST = "FETCHING_MY_PATIENT_LIST";
export const FETCHING_MY_PATIENT_LIST_FAILURE = "FETCHING_MY_PATIENT_LIST_FAILURE";
export const FETCHING_MY_PATIENT_LIST_SUCCESS = "FETCHING_MY_PATIENT_LIST_SUCCESS";

export const USER_LOGGING_IN = "USER_LOGGING_IN";
export const USER_LOGGING_IN_SUCCESS = "USER_LOGGING_IN_SUCCESS";
export const USER_LOGGING_IN_FAILURE = "USER_LOGGING_IN_FAILURE";

export const GET_ALL_USER_LIST = "GET_ALL_USER_LIST";
export const GET_ALL_USER_LIST_SUCCESS = "GET_ALL_USER_LIST_SUCCESS";
export const GET_ALL_USER_LIST_FAILURE = "GET_ALL_USER_LIST_FAILURE";

export const GET_USER_DETAIL = "GET_USER_DETAIL"
export const GET_USER_DETAIL_SUCCESS = "GET_USER_DETAIL_SUCCESS";
export const GET_USER_DETAIL_FAILURE = "GET_USER_DETAIL_FAILURE"; 

export const UPDATING_USER = "UPDATING_USER";
export const UPDATING_USER_FAILURE = "UPDATING_USER_FAILURE";
export const UPDATING_USER_SUCCESS = "UPDATING_USER_SUCCESS";

export const REGISTERING_USER = "REGISTERING_USER";
export const REGISTERING_USER_SUCCESS = "REGISTERING_USER_SUCCESS";
export const REGISTERING_USER_FAILURE = "REGISTERING_USER_FAILURE";
